/**
 * Complete list of Spanish provinces as used in empresite.eleconomista.es URLs.
 */
export const PROVINCIAS = [
    { code: 'ALAVA', name: 'Álava' },
    { code: 'ALBACETE', name: 'Albacete' },
    { code: 'ALICANTE', name: 'Alicante' },
    { code: 'ALMERIA', name: 'Almería' },
    { code: 'ASTURIAS', name: 'Asturias' },
    { code: 'AVILA', name: 'Ávila' },
    { code: 'BADAJOZ', name: 'Badajoz' },
    { code: 'BALEARES', name: 'Baleares' },
    { code: 'BARCELONA', name: 'Barcelona' },
    { code: 'BURGOS', name: 'Burgos' },
    { code: 'CACERES', name: 'Cáceres' },
    { code: 'CADIZ', name: 'Cádiz' },
    { code: 'CANTABRIA', name: 'Cantabria' },
    { code: 'CASTELLON', name: 'Castellón' },
    { code: 'CEUTA', name: 'Ceuta' },
    { code: 'CIUDAD-REAL', name: 'Ciudad Real' },
    { code: 'CORDOBA', name: 'Córdoba' },
    { code: 'CORUNA', name: 'Coruña' },
    { code: 'CUENCA', name: 'Cuenca' },
    { code: 'GERONA', name: 'Gerona' },
    { code: 'GRANADA', name: 'Granada' },
    { code: 'GUADALAJARA', name: 'Guadalajara' },
    { code: 'GUIPUZCOA', name: 'Guipúzcoa' },
    { code: 'HUELVA', name: 'Huelva' },
    { code: 'HUESCA', name: 'Huesca' },
    { code: 'JAEN', name: 'Jaén' },
    { code: 'LEON', name: 'León' },
    { code: 'LERIDA', name: 'Lérida' },
    { code: 'LUGO', name: 'Lugo' },
    { code: 'MADRID', name: 'Madrid' },
    { code: 'MALAGA', name: 'Málaga' },
    { code: 'MELILLA', name: 'Melilla' },
    { code: 'MURCIA', name: 'Murcia' },
    { code: 'NAVARRA', name: 'Navarra' },
    { code: 'ORENSE', name: 'Orense' },
    { code: 'PALENCIA', name: 'Palencia' },
    { code: 'PALMAS', name: 'Las Palmas' },
    { code: 'PONTEVEDRA', name: 'Pontevedra' },
    { code: 'RIOJA', name: 'La Rioja' },
    { code: 'SALAMANCA', name: 'Salamanca' },
    { code: 'SANTA-CRUZ-TENERIFE', name: 'Santa Cruz de Tenerife' },
    { code: 'SEGOVIA', name: 'Segovia' },
    { code: 'SEVILLA', name: 'Sevilla' },
    { code: 'SORIA', name: 'Soria' },
    { code: 'TARRAGONA', name: 'Tarragona' },
    { code: 'TERUEL', name: 'Teruel' },
    { code: 'TOLEDO', name: 'Toledo' },
    { code: 'VALENCIA', name: 'Valencia' },
    { code: 'VALLADOLID', name: 'Valladolid' },
    { code: 'VIZCAYA', name: 'Vizcaya' },
    { code: 'ZAMORA', name: 'Zamora' },
    { code: 'ZARAGOZA', name: 'Zaragoza' },
];
